# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.webcamFeed = QtWidgets.QLabel(self.centralwidget)
        self.webcamFeed.setGeometry(QtCore.QRect(20, 30, 426, 240))
        self.webcamFeed.setMinimumSize(QtCore.QSize(426, 240))
        self.webcamFeed.setMaximumSize(QtCore.QSize(426, 240))
        self.webcamFeed.setText("")
        self.webcamFeed.setObjectName("webcamFeed")
        self.consoleOutput = QtWidgets.QLabel(self.centralwidget)
        self.consoleOutput.setGeometry(QtCore.QRect(20, 300, 751, 41))
        self.consoleOutput.setText("")
        self.consoleOutput.setObjectName("consoleOutput")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 360, 771, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.beginButton = QtWidgets.QPushButton(self.centralwidget)
        self.beginButton.setGeometry(QtCore.QRect(630, 210, 113, 32))
        self.beginButton.setObjectName("beginButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 90, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 50, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 130, 111, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 170, 171, 21))
        self.label_4.setObjectName("label_4")
        self.ambientLight = QtWidgets.QLabel(self.centralwidget)
        self.ambientLight.setGeometry(QtCore.QRect(610, 50, 91, 21))
        self.ambientLight.setText("")
        self.ambientLight.setObjectName("ambientLight")
        self.blinksPerMinute = QtWidgets.QLabel(self.centralwidget)
        self.blinksPerMinute.setGeometry(QtCore.QRect(610, 90, 91, 21))
        self.blinksPerMinute.setText("")
        self.blinksPerMinute.setObjectName("blinksPerMinute")
        self.eyeStrain = QtWidgets.QLabel(self.centralwidget)
        self.eyeStrain.setGeometry(QtCore.QRect(610, 130, 91, 21))
        self.eyeStrain.setText("")
        self.eyeStrain.setObjectName("eyeStrain")
        self.brightness = QtWidgets.QLabel(self.centralwidget)
        self.brightness.setGeometry(QtCore.QRect(680, 170, 91, 21))
        self.brightness.setText("")
        self.brightness.setObjectName("brightness")
        self.calibrateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calibrateButton.setGeometry(QtCore.QRect(490, 210, 113, 32))
        self.calibrateButton.setObjectName("calibrateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eye Strain Alleviator"))
        self.beginButton.setText(_translate("MainWindow", "Begin "))
        self.label.setText(_translate("MainWindow", "Blinks/Minute:"))
        self.label_2.setText(_translate("MainWindow", "Ambient Light:"))
        self.label_3.setText(_translate("MainWindow", "Eye Strain Level:"))
        self.label_4.setText(_translate("MainWindow", "Current Display Brightness:"))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate "))
